# Error Handling(에러 처리)
- 컴파일오류(문법적 오류): 컴파일러가 코드가 잘못되었음을 알려줌
- 런타임오류: 다양한 이유로 실행되는 동안 발생. 앱이 꺼짐
- 앱이 그냥 꺼지는것보다 경고창을(ex.네트워크를 다시 확인해주세요) 통해서 알려주면 사용자 편의성이 올라간다.(사용자에게 좋은 경험?을 제공)

- 함수에다가 throws를 사용했다면 함수안쪽에서는 throw를 사용한다 return하고 비슷하다고 생각하면 됨 
- 던질 에러는 열거형이기 때문에 사용하기전에 먼저 정의를 해주어야 한다.
- 에러를 정의하려면 Error 프로토콜을 채택해야 한다.

- 에러가 발생할 수도 있는 함수를 실행할때 try와 do-catch문으로 처리
- 에러가 발생할 수 있는 함수를 실행할 때는 try를 앞에 붙인다. try는 do블럭안에서 실행해야 한다.
- do 블럭은 정상적인 경우 실행 catch 블럭은 함수가 에러를 던졌을 경우 실행
- try값이 return값이 있으면 다른 변수에 넣어서 사용하고, return 값이 없으면 그냥 사용한다.


## 에러 처리의 과정 (3단계)
```swift
// 1. 에러 정의 (어떤 에러가 발생할지 경우를 미리 정의)
enum WeightError: Error {
    case overWeight
    case underWeight
}

// 2. 에러가 발생할 수 있는 함수에 대한 정의
func checkingWeight(weight: Int) throws -> Bool {   // 파라미터와 리턴 사이에 throws를 사용
    
    if weight > 500 {
        throw WeightError.overWeight
    } else if weight < 100 {
        throw WeightError.underWeight
    } else {
        if weight >= 200 {
            return true
        } else {
            return false
        }
    }
    
}

// 3. 에러가 발생할 수 있는 함수의 실행
do {
    let isChecked = try checkingWeight(weight: 250)
    print("사과의 무게는: \(isChecked)")

} catch {
    print("판매 불가 사과입니다.")
}

// 고차 함수에서 사용
[1,2,3,4,5].map(transform: (Int) throws -> T)
정수를 받아서 어떠한 타입으로(T) 변형할 수 있는데 에러를 던질수 있는 함수
```

## 에러를 처리하는 방법 (try, try?, try!)
- try? 정상적인경우: 리턴타입으로 리턴, 에러가 발생하면: nil 리턴 / 모든 에러발생의 예외적인 경우를 디테일하게 처리 가능
- try? (옵셔널 트라이) do catch를 사용하지 않아도 됨 try를 사용하려면 옵셔널 타입을 벗겨서 사용해야함 
- try! (Forced try) 런타임에러가 발생하면 앱이 종료되므로 에러가 발생하지 않을거라고 확신할 경우에만 사용

```swift
// try
do {
    let isChecked = try checkingWeight(weight: 250)
    
    if isChecked {
        print("판매 가능한 사과입니다")
    } else {
        print("조금 자란 사과입니다.")
    }

} catch {
    print("판매 불가 사과입니다.")
}

// try?

let isChecked = try? checkingWeight(weight: 250)        // Bool?

if let result = isChecked {     // 사용시 옵셔널바인딩을 사용해야함
    print(result)
}

// try!

let isChecked: Bool = try! checkingWeight(weight: 250)  // Bool
```

## Catch블럭 처리법
- catch 블럭은 do블럭에서 발생한 에러만을 처리하는 블럭
- 반드시 모든 에러를 반드시 처리해야만 함 (글로벌 스코프에서는 모든 에러를 처리하지 않아도 컴파일 에러발생 X)
- catch문 안에는 error 라는 상수가 제공됨 (모든 에러가 넘어옴)

```swift
enum WeightError: Error {
    case overWeight
    case underWeight
}

do {
    let isChecked = try checkingWeight(height: 100)
} catch WeightError.overWeight{             // catch문에 switch문 처럼 열거형을 넣을 수 있다 
    print("apple weight over"
} catch WeightError.underWeight where{      // where 절을 추가해서 구체적인 조건도 추가 가능
    print("apple weight under")
} catch {                                   // catch문에 아무것도 안 적을 경우 default문 역할을한다.
    print("?")                              // 즉 위에 적은것외에 모든 에러는 그냥 catch문으로 처리
}
```

** error 키워드**
- catch문 안에는 error 라는 상수가 제공됨 (모든 에러가 넘어옴)
- 프로토콜도 타입이다!
- 위에처럼 (catch WeightError.overWeight) catch문에 구체적인 에러를 나열해서 매칭이됨
- 여기는 catch를 구체적인 에러에 매칭시키지 않음
- 그냥 catch문만 사용할 경우 상수인 error을 쓸 수 있다는 거임
- catch문에 ,로 여러개를 나열할 수 있게됨 Swift 5.3

```swift
enum WeightError: Error {
    case overWeight
    case underWeight
}

do {
    let isChecked = try checkingWeight(height: 100)
    } catch {             // catch문에 switch문 처럼 열거형을 넣을 수 있다 
        
        print(error)      // 이렇게 출력할 수 있고
        print(error.localizedDescription)   // 실제 앱에서는 이렇게 많이 사용함
    
    // 아래처럼 다운캐스팅해서 구체적인 에러를 다시 구체적인 에러로 변환할 수도 있다.
    // 구체적이지 않은 error 프로토콜 타입을 구체적인 열거형타입으로(WeightError) 타입캐스팅(as?)해가지고 맨앞 error 상수에 담고 있다.
    if let error = error as? WeightError {  // 프로토콜의 error을 사용 
        switch error {
        case .overWeight:
            print("사과의 무게가 크다.")
        case .underWeight:
            print("사과의 무게가 작다.")
        }
    }
}
``` 



## 에러를 던지는 함수를 처리하는 함수
```swift
// 에러정의
enum SomeError: Error {
    case aError
}

// 에러를 던지는 함수 정의 (무조건 에러를 던진다고 가정)
func throwingFunc() throws {
    throw SomeError.aError
}

// 에러의 처리
do{
    try throwingFunc()
} catch {
    print(error)
}
```

1) 일반적인 함수로 처리
- 함수 내부에서 do-catch문으로 에러를 처리
- 발생한 에러를 catch 블럭에서 처리함
- 일반적으로 do-catch문으로 에러를 처리가능하지만 함수 안에서도 에러를 처리할 수 있음
```swift
func handleError() {
    do{
        try throwingFunc()
    } catch {
        print(error)
    }
}

handleError()
```
2) 에러 다시 던지기
- 함수 내에서 에러를 직접처리하지 못하는 경우, 에러를 다시 던질 수 있음
```swift
func handleError() throws {
   do {
        try throwingFunc()
    }                 // catch블럭이 없어도 에러를 밖으로 던질 수 있음
}                     // 던진에러는 따로 다른곳에서 처리해야함

func handleError() throws {
    try throwingFunc()  // try하나만 사용할 시 do 블럭 생략 가능
}


```
3) rethrows 키워드
- 에러를 던지는 throwing 함수를 파라미터로 받는 경우, 내부에서 다시 에러를 던지기 가능
- 함수를 파라미터로 사용할 때는 다시 던진다는 의미에서 rethrows 사용
- rethrows를 정의한 함수를 Rethrowing메서드, Rethrowing함수 라고도 부른다. 
```swift
func someFunction(callback: () throws -> Void) rethrows {   // do 문이 생략되어 있다.
    try callback()
}

func someFunction(some: () throws -> Void) rethrows {   // 파라미터이기 때문에 이름 변경 가능
    try some()
}

// someFunction의 파라미터를 보면 함수형타입이다.
// someFunction은 고차함수다 고차함수는 함수를 파라미터로 사용하거나 파라미터를 아웃풋으로 던질수 있는 함수이다.
```

- 이거는 약간 어거지로 만들어진거?
```swift
func someFunction1(callback: () throws -> Void) rethrows {
    
    enum ChangedError: Error {  // 내부에서 또 다른 에러 함수를 다시 정의함
        case cError
    }
    
    do {
        try callback()      // callback 함수를 호출하면 실제 에러가 발생해서 catch문으로 갈것이다. 그러면 catch문으로 다시 던짐
    } catch {                           // catch문에서는 throw
        throw ChangedError.cError       // 에러를 변환해서 다시 던짐
    }
    
}


```

## 메서드 / 생성자
- 메서드나 생성자도 함수이기 때문에 throw 키워드를 적용할 수 있다.
- 일반함수가 범위가 더 크고 에러를 던질 수 있는 함수가 범위가 더 적다. rethrows는 범위가 더 적다.

```swift
enum NameError: Error {
    case noName
}

class Fruit {
    var name: String
    
    init(name: String) throws { // 에러를 던질 수 있는 생성자
        if name == "" {
            throw NameError.noName
        }else {
            self.name = name
        }
    }
    
}

do {
// 사용해야 하닌깐 변수에 담는다.
    var apple = try Fruit(name: "apple")    // 에러를 발생시킬수도 있는 붕어빵을 찍어낸거임
} catch NameError.noName{
    print("이름이 없음")
}


class Food: Fruit {     // 위에 Fruit를 상속

    override init(name: String) throws {    // 에러를 발생할 수 있는 생성자 이기때문에 반드시 throws 사용
        try super.init(name: name)      // try로 호출해야함
    }

}
```

## Defer문
- 할일을 미룸
- 나를 감싸고 있는 스코프가 종료되는 시점으로 연기시킴
- 디퍼문은 꼭 한번은 실행되야 종료가 예약되는 개념
- 여러개를 실행할 경우 등록한거에 역순으로 실행, 그래서 일반적으로 하나의 디퍼문만 사용하는것이 좋음
- 실전에서는 코드가 길어지면 헷갈릴수 있기때문에 반드시 실행시킬것들은 미리 예약 해놓는것(겨우 이런이유때문에?)

```swift
func deferFunc() {
    defer {
        print("나중에 실행하기")
    }
    print("먼저 실행하기")
}   

먼저실행하기, 나중에실행하기 순으로 실행
```
